// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfhvR2E8HstSt4PVluKUmjvUku65GQAc',
    appId: '1:161805077597:web:db75c4879fdf0719a5d1b4',
    messagingSenderId: '161805077597',
    projectId: 'jarnama-app-bddb2',
    authDomain: 'jarnama-app-bddb2.firebaseapp.com',
    storageBucket: 'jarnama-app-bddb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0VxjIlmfBQL-QIew5tC1ejfYiJ0hE7c',
    appId: '1:161805077597:android:372fc2765e648220a5d1b4',
    messagingSenderId: '161805077597',
    projectId: 'jarnama-app-bddb2',
    storageBucket: 'jarnama-app-bddb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaqfNgfnCBH40QVofo2Q9vh-bQJvJBdM',
    appId: '1:161805077597:ios:e6d95ff3de8b541aa5d1b4',
    messagingSenderId: '161805077597',
    projectId: 'jarnama-app-bddb2',
    storageBucket: 'jarnama-app-bddb2.appspot.com',
    iosClientId: '161805077597-4l30d495vupcjjs9l7c949eccssoehan.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaqfNgfnCBH40QVofo2Q9vh-bQJvJBdM',
    appId: '1:161805077597:ios:584dfa958ee62bfea5d1b4',
    messagingSenderId: '161805077597',
    projectId: 'jarnama-app-bddb2',
    storageBucket: 'jarnama-app-bddb2.appspot.com',
    iosClientId: '161805077597-sdiukre9uvtopg2jf3s0ji1g6tmouqt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama.RunnerTests',
  );
}
